// Package main provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package main

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
)

// KeepRequest defines model for KeepRequest.
type KeepRequest struct {
	// Prompt The base prompt you want to build a keep for
	Prompt string `json:"prompt"`

	// RandomiseXmlTag Whether to randomise the XML tag that is used to escape user input in your prompt.
	RandomiseXmlTag *bool `json:"randomise_xml_tag,omitempty"`
}

// KeepResponse defines model for KeepResponse.
type KeepResponse struct {
	// ShieldedPrompt The shielded prompt.
	ShieldedPrompt string `json:"shielded_prompt"`

	// XmlTag The XML tag that is used to escape user input in your prompt.
	XmlTag string `json:"xml_tag"`
}

// User defines model for User.
type User struct {
	// UserId The user ID of the suspicious user.
	UserId *string `json:"userId,omitempty"`
}

// WallRequest defines model for WallRequest.
type WallRequest struct {
	// CheckBadwords Whether to scan for badwords in the prompt.
	CheckBadwords *bool `json:"check_badwords,omitempty"`

	// FastCheck Whether to perform a fast check on the prompt instead of a full check.
	FastCheck *bool `json:"fast_check,omitempty"`

	// Prompt The text prompt to be verified.
	Prompt string `json:"prompt"`

	// ScanPii Whether to scan for PII in the prompt.
	ScanPii *bool `json:"scan_pii,omitempty"`

	// SessionId The session ID of the user who is submitting the prompt. This is used to flag suspicious sessions
	SessionId *string `json:"session_id,omitempty"`

	// UserId The user ID of the user who is submitting the prompt. This is used to flag suspicious users
	UserId *string `json:"user_id,omitempty"`

	// XmlTag The XML tag that is used to escape user input in your prompt (this may have been generated with keep).
	XmlTag *string `json:"xml_tag,omitempty"`
}

// WallResponse defines model for WallResponse.
type WallResponse struct {
	// ContainsPii Whether the prompt contains PII.
	ContainsPii *bool `json:"contains_pii,omitempty"`

	// PotentialJailbreak Whether the prompt contains a potential jailbreak.
	PotentialJailbreak *bool `json:"potential_jailbreak,omitempty"`

	// PotentialXmlEscaping Whether the prompt contains potential XML escaping.
	PotentialXmlEscaping *bool `json:"potential_xml_escaping,omitempty"`

	// SuspiciousSession Whether the session is suspicious.
	SuspiciousSession *bool `json:"suspicious_session,omitempty"`

	// SuspiciousUser Whether the user is suspicious.
	SuspiciousUser *bool `json:"suspicious_user,omitempty"`
}

// BuildKeepJSONRequestBody defines body for BuildKeep for application/json ContentType.
type BuildKeepJSONRequestBody = KeepRequest

// AddUserJSONRequestBody defines body for AddUser for application/json ContentType.
type AddUserJSONRequestBody = User

// BuildWallJSONRequestBody defines body for BuildWall for application/json ContentType.
type BuildWallJSONRequestBody = WallRequest
