# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Deploy

permissions:
  id-token: write 
  contents: read  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: make build

    - name: Test
      run: make test 
      
  deploy:
      runs-on: ubuntu-latest
      environment: production
      timeout-minutes: 10
      steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::478910673833:role/GithubActionsStr
          aws-region: eu-west-1
          role-session-name: MySessionName

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
      - name: Build
        run: make build
      - name: Deploy
        env:
          TF_VAR_openai_secret_key: ${{ secrets.OPENAI_API_KEY }}
        run: make deploy 
