name: PR

permissions:
  id-token: write
  contents: read
on:
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  integration_test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::478910673833:role/GithubActionsStr
          aws-region: eu-west-1
          role-session-name: MySessionName

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
      - name: Deploy
        run: make setup-workspace
        env:
          TF_VAR_openai_secret_key: ${{ secrets.OPENAI_API_KEY }}
          open_ai_api_key: ${{ secrets.OPENAI_API_KEY }}

#      - name: Destroy
#        run: make destroy
#        if: always()
#        env:
#          TF_VAR_openai_secret_key: ${{ secrets.OPENAI_API_KEY }}

